# Generated by Django 5.2.1 on 2025-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="pager",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="staff_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
