# Generated by Django 5.2.1 on 2025-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofiles",
            "0002_remove_userprofile_pager_remove_userprofile_staff_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
