# Generated by Django 5.2.1 on 2025-06-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0003_userprofile_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
