# Generated by Django 5.2.1 on 2025-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="issue",
            name="category",
            field=models.CharField(
                choices=[
                    ("product_design", "Product design"),
                    ("development", "Development"),
                    ("qa_testing", "QA & Testing"),
                    ("customer_queries", "Customer queries"),
                    ("r_and_d", "R & D"),
                ],
                default="product_design",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
