# Generated by Django 5.2.1 on 2025-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_name_project_title_issue_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXPLORING", "Exploring"),
                    ("RESEARCH", "Research"),
                    ("DEVELOPMENT", "Development"),
                    ("TESTING", "Testing"),
                    ("DEPLOYMENT", "Deployment"),
                    ("MAINTENANCE", "Maintenance"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
