# Generated by Django 5.2.1 on 2025-06-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_project_category_alter_project_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
