# Generated by Django 5.2.1 on 2025-07-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_project_budget_project_client_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="short_description",
        ),
        migrations.AddField(
            model_name="task",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
