# Generated by Django 4.1.7 on 2025-07-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
