# Generated by Django 4.1.7 on 2025-07-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_project_completed_project_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="project_files/"),
        ),
    ]
