# Generated by Django 4.1.7 on 2025-08-01 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0004_remove_userprofile_email"),
        ("project", "0008_project_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="project_files/")),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_files",
                        to="project.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userprofiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project File",
                "verbose_name_plural": "Project Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("FILE_UPLOAD", "File Upload"),
                            ("TASK_CREATED", "Task Created"),
                            ("TASK_COMPLETED", "Task Completed"),
                            ("TASK_REOPENED", "Task Reopened"),
                            ("PROJECT_COMPLETED", "Project Completed"),
                            ("PROJECT_REOPENED", "Project Reopened"),
                            ("PROJECT_UPDATED", "Project Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userprofiles.userprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="project.project",
                    ),
                ),
                (
                    "related_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.projectfile",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Activity",
                "verbose_name_plural": "Project Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
