# Generated by Django 4.1.7 on 2025-08-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_projectfile_projectactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("PROJECT_CREATED", "Project Created"),
                    ("FILE_UPLOAD", "File Upload"),
                    ("TASK_CREATED", "Task Created"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("TASK_REOPENED", "Task Reopened"),
                    ("PROJECT_COMPLETED", "Project Completed"),
                    ("PROJECT_REOPENED", "Project Reopened"),
                    ("PROJECT_UPDATED", "Project Updated"),
                ],
                max_length=20,
            ),
        ),
    ]
