[mysql]
ENGINE=django.db.backends.mysql
NAME=proj
USER=root
PASSWORD=Wyyzzqt2021!
HOST=127.0.0.1
PORT=3306

[keys]
SECRET_KEY=ghjgffsdfsdfs#c55#sdfsf

[deployment]
status=development
debug=true
with_debug_toolbar=true
template_debug=true
allowed_hosts=localhost,127.0.0.1

[logging]
directory=/Users/zhongyu/Projects/Web_app/proj_portal/logs/

[email]
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=localhost
EMAIL_PORT=25
EMAIL_HOST_USER=admin
EMAIL_HOST_PASSWORD=1234
EMAIL_USE_TLS=false
#DEFAULT_FROM_EMAIL=T2D <rc2@rc2.cri.uchicago.edu>
DEFAULT_FROM_EMAIL=
host_url=http://localhost:8000


[static]
STATIC_ROOT=/Users/zhongyu/Desktop/Web_app/proj_portal/proj_management/static/
MEDIA_ROOT=/Users/zhongyu/Desktop/Web_app/proj_portal/static/media

