# Generated by Django 5.2.1 on 2025-05-30 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="User ID"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("pager", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user_level",
                    models.CharField(
                        choices=[
                            ("TECH", "Technologist"),
                            ("MS", "Manager/supervisor"),
                            ("D", "Director"),
                            ("SA", "Super Admin"),
                        ],
                        default="TECH",
                        max_length=4,
                        verbose_name="role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__last_name", "user__first_name"),
            },
        ),
    ]
